version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    ports:
      - 80:80
    depends_on:
      - app

  app:
    build:
      context: .
      container_name: laravel-app
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      DB_DATABASE: jinjer_talent
      DB_USERNAME: root
      DB_PASSWORD: pass
    ports:
      - 3306:3306

volumes:
  db_data:
